name: "Maintenance: Stale Bot"

on:
  schedule:
    - cron: '30 1 * * *' # Every day at 1:30 am
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest # Allowed for housekeeping
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Issues configurations
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-stale: 30
          days-before-close: 14
          
          # PR configurations
          stale-pr-message: "This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          close-pr-message: "This PR was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-stale: 45
          days-before-pr-close: 14

          # Critical Exemptions
          exempt-issue-labels: "override-stale,bug,help wanted"
          exempt-pr-labels: "dependencies,requires-changeset"
          stale-issue-label: "status: stale"
          stale-pr-label: "status: stale"